### PR TITLE
Fix/fb review

### PR DESCRIPTION
**Pull request by lmichel**
This PR comes as an answer if the @Bonnarel review issued in the dm list on Dec 22.
It contains clarifications of the ATTRIBUTE@ref, the COLLECTION purpose and the dynamic references

### CODE REVIEW

**Review by loumir — COMMENTED** [review]
_in element_collection.tex line 1: I don't quite understand this sentence :_ 
It is used in different contexts, each allowing a limited subset of elements for its content. 
_in element_reference.tex line 16:_  
  If the \texttt{REFERENCE} has multiple \texttt{FOREIGN\_KEY}-s, they must *BE* evaluated 
           against the target \texttt{PRIMARY\_KEY}-s in order of occurrence.

**Comment by lmichel** [comment]
> If the \texttt{REFERENCE} has multiple \texttt{FOREIGN_KEY}-s, they must BE evaluated
> against the target \texttt{PRIMARY_KEY}-s in order of occurrence.

fixed

**Comment by lmichel** [comment]
I do not see what is not clear with  _element_collection.tex line 1:_

**Comment by Bonnarel** [comment]
I agree with the changes you propose. I propose two more additions
1 ) In element_attribute before the modified/added text by Laurent also add a clarifaction on what the dmtype does

> This dmtype may complete missing types in the VOTable. In case of inconsistency with VOTable
> dmtype SHOULD supersede VOTable types.

2 )  in element_reference for Dynamic reference, after " Dynamic reference: The element has a @sourceref attribute identifying the foreign collection (TEMPLATES or COLLECTION) containing the referenced INSTANCE" which explains that sourceref points to a gathering INSTANCES I suggest to add this clarification to where the id of the INSTANCE can be found. 

> The id of this INSTANCE is given by included  FOREIGN_KEY element.

**Comment by lmichel** [comment]
FB comment fixed

**Review by Bonnarel — APPROVED** [review]

**Comment by Bonnarel** [comment]
Changes seem all good. Go ahead

**Pull request merged**
