### PR TITLE
improvement suggestions /.tex 

### PR DESCRIPTION
**Pull request by loumir**
introduction.tex
mivot.tex --> section for XSD reference 
simplified role_diagram.pdf

### CODE REVIEW

**Comment by lmichel** [comment]
The architecture diagram must include VOUnit (mentioned in the ATTRIBUTE section)

**Comment by lmichel** [comment]
There is no need to comment out the text you have modified. 
It is supposed to make the review easier, but it makes it harder from the GitHub page actually

**Comment by mcdittmar** [comment]
>introduction:
>
> \item UTypes constrain to single-table serializations. All model elements must  be contained within the same VOTable TABLE.
>
>   % mir ??? not clear enough : prov dm has many tables with well defined utypes 

The example that comes to mind right away is that you cannot spread a Spectrum out among different TABLEs, say to serialize each order in a different TABLE (not sure you'd want to, but you can't).  The spec:Spectrum UType is assigned to a TABLE element, by definition and so all content must be within that same TABLE.

**Comment by loumir** [comment]
thanks Mark , 
very good example . 
the spectrum object cannot extend its parts in multiple tables . 
should we use it as an illustration for this requirement?

**Review by lmichel — APPROVED** [review]

**Review by lmichel — APPROVED** [review]

**Pull request merged**
